### ISSUE TITLE
Examples use deprecated constructors for KmsMasterKeyProvider.

### ISSUE THREAD

**Issue by lizroth** [aws/aws-encryption-sdk-java#145]
https://aws.github.io/aws-encryption-sdk-java/javadoc/com/amazonaws/encryptionsdk/kms/KmsMasterKeyProvider.html shows that most constructors for `KmsMasterKeyProvider` are deprecated in favor of https://aws.github.io/aws-encryption-sdk-java/javadoc/com/amazonaws/encryptionsdk/kms/KmsMasterKeyProvider.Builder.html , but `EscrowedEncryptExample.java` uses some of those deprecated constructors still (e.g. https://github.com/aws/aws-encryption-sdk-java/blob/master/src/examples/java/com/amazonaws/crypto/examples/EscrowedEncryptExample.java#L83 ).

**Comment by lavaleri** [comment]
All examples should now be using the builder pattern.
