### ISSUE TITLE
Update tests to use JUnit 5 assertions

### ISSUE THREAD

**Issue by WesleyRosenblum** [aws/aws-encryption-sdk-java#157]
Now that the Java ESDK uses JUnit 5 for testing (post Keyring integration), many of the old tests could benefit from using org.junit.jupiter.api.Assertions.assertThrows and generally being upgraded to make use of JUnit 5 features.

**Comment by mattsb42-aws** [comment]
🎉  https://www.baeldung.com/parameterized-tests-junit-5 🎉

**Comment by WesleyRosenblum** [comment]
> 🎉 https://www.baeldung.com/parameterized-tests-junit-5 🎉

I've already updated `TestVectorRunner` to be a JUnit 5 parameterized test: https://github.com/aws/aws-encryption-sdk-java/blob/28aeee28868f067c92fbaeed74e8e3c490a6b2f1/src/test/java/com/amazonaws/encryptionsdk/TestVectorRunner.java#L74

**Comment by waikontse** [comment]
Hi,

I'm interested in taking this task on, is it still open?
And another question, as I didn't take a look at the whole code base yet, is there a figure on how many test cases there are in total? 
Thanks.

**Comment by acioc** [comment]
Thanks for the interest! Much of this work has already been done in our `keyring` branch, which will be released in the future. This includes a migration to JUnit 5, as noted by Wesley above.

Whenever a pull request is cut against the repository, we have Travis tests that run. For example, in our last merge into the `keyring` branch, you can see the build/test results (https://travis-ci.org/github/aws/aws-encryption-sdk-java/jobs/733507555), which show we have 8860 tests (these include both traditional unit tests as well as test vectors and integration tests, including running our examples).

It's a bit difficult to get a full "coverage" report, but running just the unit tests locally (6,127 tests) shows an IDE-reported coverage of 90% class, 88% method, and 90% line coverage. We additionally have our examples and test vectors that run in Travis.

We're leaving this issue open until we merge the `keyring` branch, but are updating the project to better reflect this and removing the 'good first issue' label.
