### ISSUE TITLE
AWSCredentialsProvider Not Found

### ISSUE THREAD

**Issue by stephendanielxxx** [aws/aws-encryption-sdk-java#1591]
Hi, 

I keep getting this error when try to integrate to Spring Boot Project.

java.lang.ClassNotFoundException: com.amazonaws.auth.AWSCredentialsProvider
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[na:na]
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188) ~[na:na]

Is there any solution for this?

**Comment by ShubhamChaturvedi7** [comment]
Hi,

This generally happens when the dependency was present during the build but is missing from the runtime classpath. Unfortunately, this is very specific to the project structure. You could look into Java's classpath param to configure this properly.
