### ISSUE TITLE
[keyring] Verify that KMS keyring behaves correctly on encrypt

### ISSUE THREAD

**Issue by mattsb42-aws** [aws/aws-encryption-sdk-java#164]
Once https://github.com/awslabs/aws-encryption-sdk-specification/issues/73 is resolved, we need to verify that the KMS keyring implementation is correct.

**Comment by lavaleri** [comment]
Keyrings are not supported in this library yet: https://github.com/aws/aws-encryption-sdk-java/issues/102
We are pursuing another mechanism to ensure that the implementation meets the specification.
