### ISSUE TITLE
[keyrings] Update example descriptions to reference "AWS KMS keyring"

### ISSUE THREAD

**Issue by mattsb42-aws** [aws/aws-encryption-sdk-java#176]
Per https://github.com/awslabs/aws-encryption-sdk-specification/issues/67, we are going to rename the KMS keyring to the AWS KMS keyring to be explicitly clear that this keyring interacts with the AWS Key Management Service, rather than some other KMS.

This does not impact the Java code, but does impact the descriptions in the examples.

**Comment by acioc** [comment]
Spec issue merged. Spec issue tracking the completion of this implementation in https://github.com/awslabs/aws-encryption-sdk-specification/issues/127 (adding link here so it properly links and shows up as closed)
