### ISSUE TITLE
AwsKmsMrkAwareMasterKeyProvider always attempts to resolve defaultRegion through DefaultAwsRegionProviderChain

### ISSUE THREAD

**Issue by spennymac** [aws/aws-encryption-sdk-java#1768]
### Problem:

After being unable to decrypt data with a multi-region key (MRK), I discovered that I needed to use the AwsKmsMrkAwareMasterKeyProvider. However, after making this change, I noticed increased latency. This was because `getDefaultRegion()` was being called every time the provider was instantiated, even when I had supplied a default region to the builder [[0]](https://github.com/aws/aws-encryption-sdk-java/blob/master/src/main/java/com/amazonaws/encryptionsdk/kmssdkv2/AwsKmsMrkAwareMasterKeyProvider.java#L50). 

`getDefaultRegion` tries to determine the region first from the system settings, then from the AWS profile, and finally from the metadata server. I haven't configured any of these, so the increased latency was due to the call to the metadata server timing out, since I'm not operating within the AWS infrastructure.

This all leads me to a question:

Could this code change to only resolve the default region in the constructor if default regions is null? Or each `build` method of the Builder calls this if the region was not set. If yes, I'll gladly put on a PR.

Thanks in advance!

**Comment by spennymac** [comment]
I understand there are many work around I can do, i just found it odd that it would attempt to resolve the the region even when you set it in the builder.

**Comment by seebees** [comment]
Hi, thanks for the report.

I think I see what is going on and how to fix it.
The expense of calling `getSdkDefaultRegion()` can and should be deferred until needed.

**Comment by seebees** [comment]
As of 3.0.0, the AWS Encryption SDK for Java is integrated with AWS Cryptographic Materials Provider (MPL).

The MPL features Keyrings, which give you much more granular control over when an SDK client is created.

You can replace your MasterKeyProvider instances with Keyrings, which will best resolve this issue.
