### ISSUE TITLE
Intermittent exception in thread "main" com.amazonaws.encryptionsdk.exception.CannotUnwrapDataKeyException: Unable to decrypt any data keys

### ISSUE THREAD

**Issue by abhijeet-srivastava** [aws/aws-encryption-sdk-java#1805]
Problem:
While trying to decrypt a secure encrypted value, I am intermittently getting this error-

```
com.amazonaws.encryptionsdk.exception.CannotUnwrapDataKeyException: Unable to decrypt any data keys
|	at com.amazonaws.encryptionsdk.MasterKeyProvider.buildCannotDecryptDksException(MasterKeyProvider.java:102)
|	at com.amazonaws.encryptionsdk.kms.KmsMasterKeyProvider.decryptDataKey(KmsMasterKeyProvider.java:504)
|	at com.amazonaws.encryptionsdk.DefaultCryptoMaterialsManager.decryptMaterials(DefaultCryptoMaterialsManager.java:118)
|	at com.amazonaws.encryptionsdk.internal.DecryptionHandler.readHeaderFields(DecryptionHandler.java:621)
|	at com.amazonaws.encryptionsdk.internal.DecryptionHandler.<init>(DecryptionHandler.java:111)
|	at com.amazonaws.encryptionsdk.internal.DecryptionHandler.create(DecryptionHandler.java:302)
|	at com.amazonaws.encryptionsdk.AwsCrypto.decryptData(AwsCrypto.java:511)
|	at com.amazonaws.encryptionsdk.AwsCrypto.decryptData(AwsCrypto.java:502)
|	at com.amazonaws.encryptionsdk.AwsCrypto.decryptData(AwsCrypto.java:476)
```

This error occurs intermittently and can be auto  resolved.

**Comment by abhijeet-srivastava** [comment]
Underlying exception is Caused by: com.amazonaws.AbortedException: 
|	at com.amazonaws.internal.SdkFilterInputStream.abortIfNeeded(SdkFilterInputStream.java:61)
|	at com.amazonaws.internal.SdkFilterInputStream.markSupported(SdkFilterInputStream.java:125)
|	at com.amazonaws.http.RepeatableInputStreamRequestEntity.isRepeatable(RepeatableInputStreamRequestEntity.java:139)
|	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.shouldRetry(AmazonHttpClient.java:1640)
|	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleRetryableException(AmazonHttpClient.java:1223)
|	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1165)
|	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:814)
|	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:781)
|	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:755)
|	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:715)
|	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:697)
|	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:561)
|	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:541)
|	at com.amazonaws.services.kms.AWSKMSClient.doInvoke(AWSKMSClient.java:9452)
|	at com.amazonaws.services.kms.AWSKMSClient.invoke(AWSKMSClient.java:9419)
|	at com.amazonaws.services.kms.AWSKMSClient.invoke(AWSKMSClient.java:9408)
|	at com.amazonaws.services.kms.AWSKMSClient.executeDecrypt(AWSKMSClient.java:2199)
|	at com.amazonaws.services.kms.AWSKMSClient.decrypt(AWSKMSClient.java:2168)
|	at com.amazonaws.encryptionsdk.kms.KmsMasterKey.decryptDataKey(KmsMasterKey.java:170)
|	at com.amazonaws.encryptionsdk.kms.KmsMasterKeyProvider.decryptDataKey(KmsMasterKeyProvider.java:498)
|	at com.amazonaws.encryptionsdk.DefaultCryptoMaterialsManager.decryptMaterials(DefaultCryptoMaterialsManager.java:118)
|	at com.amazonaws.encryptionsdk.internal.DecryptionHandler.readHeaderFields(DecryptionHandler.java:621)
|	at com.amazonaws.encryptionsdk.internal.DecryptionHandler.<init>(DecryptionHandler.java:111)
|	at com.amazonaws.encryptionsdk.internal.DecryptionHandler.create(DecryptionHandler.java:302)
|	at com.amazonaws.encryptionsdk.AwsCrypto.decryptData(AwsCrypto.java:511)
|	at com.amazonaws.encryptionsdk.AwsCrypto.decryptData(AwsCrypto.java:502)
|	at com.amazonaws.encryptionsdk.AwsCrypto.decryptData(AwsCrypto.java:476)

**Comment by lucasmcdonald3** [comment]
Hi @abhijeet-srivastava,

The AWS SDK for Java will raise an [AbortedException](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/AbortedException.html) if the calling thread is interrupted while it's executing the request. This exception comes from the KMS client used by your decrypt calls.

The intermittent nature of this exception points toward a network issue in your environment.
You can enable [AWS Java SDK Metrics](https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/generating-sdk-metrics.html) and its [Latency Metrics Logging](https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/java-dg-logging.html#sdk-latency-logging) feature to help identify a possible network issue.

Another possibility: if you are working in a multithreaded environment, your application may be unintentionally interrupting the calling thread.

You can also consider adding retry logic to handle occasional instances of this exception so they do not interrupt your program.
The `AbortedException` has an `isRetryable` method on it to indicate whether you can retry the call.
I would suggest catching these exceptions and checking `isRetryable`.
If `isRetryable` is `true`, retry the call (with delays, backoff, retry count limit, etc. based on your application use case).

Best,
Lucas
