### ISSUE TITLE
Support KMS asymmetric keys

### ISSUE THREAD

**Issue by ajhool** [aws/aws-encryption-sdk-java#181]
It does not appear that the Encryption SDK supports KMS asymmetric keys (eg. GenerateDataKeyPair ) , so, two requests:

- Native support for KMS asymmetric keys
- If possible, a keyring example for using KMS Asymmetric Data keys

**Comment by mattsb42-aws** [comment]
Hi @ajhool, thanks for the request!

Could you elaborate a bit on the use-case that this would address? We have looked at the idea of what an AWS KMS asymmetric keyring would look like, but it would help to have real-world scenarios. Ex: would you want KMS to do both encrypt and decrypt or encrypt locally and decrypt with KMS? If the former, you would probably be better served by using a symmetric CMK.

**Comment by ajhool** [comment]
@mattsb42-aws Thanks for the response, my two use-cases are as follows:

**Use-case 1: Encrypt a file on the client (standalone java program) and upload to S3. The file can then be decrypted within the AWS account. The decryption key never leaves AWS unencrypted.**

    1. Client requests a KMS data public key and the KMS encrypted private key using the GenerateDataKeyPairWithoutPlaintext command.
    2. Client Platform encrypts the files using the public key. (How in the world is encryption done in a java program?)
    3. Client uploads the encrypted file to S3 along with the encrypted private data key (envelope encryption)
    4. AWS-side decryption: KMS used to decrypt the private data key, then the private data key is used to decrypt the data

**Use-case 2: Encrypt a file that is already in S3 and decrypt it on the client (standalone java program) using an asymmetric key.**

    1. Client must generate the data key pair. This could be done client-side, but will instead use the GenerateDataKeyPair command to return an unencrypted public key and an unencrypted private key. (Is there an easier way to generate an asymmetric key pair in the java program so that the private key does not leave prem?)
    2. Client will upload the public key to KMS (aka KMS will import the key).
    3. Client will request that S3 performs a COPY to encrypt the file using the newly uploaded KMS key.
    4. Client will retrieve the newly copied file and use the private key from step 1 to decrypt it.

**Comment by mattsb42-aws** [comment]
> Use-case 1: Encrypt a file on the client (standalone java program) and upload to S3. The file can then be decrypted within the AWS account. The decryption key never leaves AWS unencrypted.

Do you specifically want to use asymmetric data keys (`GenerateDataKeypair`)? Asymmetric CMKs seem like they would be a better fit for what you're describing (note: we would still need a different keyring to work with asymmetric CMKs).

> Use-case 2: Encrypt a file that is already in S3 and decrypt it on the client (standalone java program) using an asymmetric key.

KMS does not support importing asymmetric CMKs[1]. What you describe seems like a better fit for the raw RSA keyring, given that you want offline decrypt capabilities.

[1] https://docs.aws.amazon.com/kms/latest/APIReference/API_ImportKeyMaterial.html

**Comment by ajhool** [comment]
@mattsb42-aws FIrst, thank you for the suggestions. Frankly, I know very little about generating keys in code and encrypting/decrypting data in code so my understanding about the asymmetric data keys comes from reading the KMS documentation and the idea that I want to encrypt large data files. I'm open to ideas!

The Java client program is also being deployed to client servers and I do not want those clients to have easy access to the keys, which is why I was hoping to use KMS to generate & manage the keys so that they can be retrieved in memory. I understand that if the AWS credentials are exposed then those KMS calls can be made outside of the program, but I'm more confident in my ability to keep credentials secure than to work with keyrings (no experience there). Data is only encrypted/decrypted while the program is in operation (~1 hour) and then all data and keys are purged from the client and the data keys are not reused for follow up queries.

> Do you specifically want to use asymmetric data keys (GenerateDataKeypair)? Asymmetric CMKs seem like they would be a better fit for what you're describing (note: we would still need a different keyring to work with asymmetric CMKs).

There are two reasons that I thought asymmetric data keys make more sense. (1) CMKs only encrypt data up to 4kb and my java client will be uploading a large data file (~10MB); thus, a public data key would make more sense for that encryption step as I understand it and (2) asymmetric CMKs do not work with the AWS KMS service integrations. So I would use a symmetric CMK and asymmetric data keypairs + envelope encryption.

This seems to me like the exact use case where asymmetric data keys + envelope encryption would be used so I must be missing something?

> KMS does not support importing asymmetric CMKs[1]. What you describe seems like a better fit for the raw RSA keyring, given that you want offline decrypt capabilities.

Good to know. My goal was to generate a data key pair in memory (either in the java client program or where the java client program makes a call to AWS KMS and stores the result in memory). These data keys are supposed to be short lived just to encrypt/decrypt data as needed while the program executes. Then, when the program is compete, the data is all discarded and so are the data keys.

How would a raw RSA Keyring allow the files to be encrypted while they sit in S3 or server side before they are transmitted to the client?

**Comment by ajhool** [comment]
@mattsb42-aws Additionally, are the suggestions that you listed already implemented in AWS Encryption SDK? Could I try them out?

**Comment by mattsb42-aws** [comment]
Just to clarify something that I assumed from your initial question:

Do you want the client in either scenario to be able to encrypt or decrypt without making calls to KMS?

From your initial question I assumed you were looking for offline operation, but your more recent description sounds like you just want the separation of permissions and are ok with both ends needing to call KMS. If that is the case, then using a symmetric KMS CMK and managing the permissions of the two actors to give you the permissions separation sounds like the better option for you.

> There are two reasons that I thought asymmetric data keys make more sense. (1) CMKs only encrypt data up to 4kb and my java client will be uploading a large data file (~10MB); thus, a public data key would make more sense for that encryption step as I understand it and (2) asymmetric CMKs do not work with the AWS KMS service integrations. So I would use a symmetric CMK and asymmetric data keypairs + envelope encryption.

Envelope encryption is precisely the problem that the AWS Encryption SDK (ESDK) addresses, yes. :)

https://docs.aws.amazon.com/encryption-sdk/latest/developer-guide/how-it-works.html

> I also notice that keyrings only seem to be supported in C and Javascript. I think that we can work with that but just wanted to confirm that we would need Node.js to use them instead of Java?

Keyrings (and master key providers) are the component of the ESDK that you can use to define how the ESDK protects your data keys, and are only intended for use with the ESDK. We designed keyrings to replace master key providers in order to provide a simpler interface and better separation of duties, but (for now at least) you can do most things that you could with keyrings with a comparable master key provider. We are working on getting keyrings ready for release in Java and Python, but until then you can use master key providers.

You can read more about keyrings and how they relate to master key providers here: https://docs.aws.amazon.com/encryption-sdk/latest/developer-guide/choose-keyring.html

You can also read more about master key providers and how they fit into the ESDK here: https://docs.aws.amazon.com/encryption-sdk/latest/developer-guide/concepts.html#master-key-provider
---

If you want to use the AWS Encryption SDK with a symmetric KMS CMK, you should look into `KMSMasterKeyProvider`[1] and `KMSMasterKey`[2].

[1] https://aws.github.io/aws-encryption-sdk-java/javadoc/com/amazonaws/encryptionsdk/kms/KmsMasterKeyProvider.html
[2] https://aws.github.io/aws-encryption-sdk-java/javadoc/com/amazonaws/encryptionsdk/kms/KmsMasterKey.html

**Comment by ajhool** [comment]
Ah, okay sorry for the confusion.

Yes, it is okay for both the client and the cloud to make KMS calls. The two underlying goals are that a file must be encrypted on one side, sent to the other side, and decrypted there. This happens in both directions, with different files, at different points in time.

Ideally, a private key wouldn't be sent over the network but I understand that to encrypt in AWS and decrypt on the client, then the private key must be sent.

**First use case:** Encrypting a file with a public data key on the client, uploading it to AWS, and decrypting it there. It is clear to me that this is the use-case that AWS has designed for. If I understand correctly, the AWS Encryption SDK does currently support a symmetric KMS key with asymmetric data keys, which is how we should be doing this (please confirm). Great. In that case we can and should use the Encryption SDK.

Second use case: Generate a file on AWS and encrypt it while it is in AWS, download it from AWS, and decrypt it with a private data key on the client. Ideally, the encryption would happen with a public data key. I don't believe that AWS has designed for this particular use-case (please let me know if that is wrong!).

I think I now understand your RSA keyring recommendation, so that the private + public data key can be generated by the client and then the public data key can be uploaded to AWS. In this use-case, offline decrypt might actually enable a few use-cases for us so that might be good to know. If the RSA keyring makes it convenient to generate an asymmetric data key on the client, I think we would then upload the public key to AWS (through an indirect/offline channel), perform the encryption by doing a Copy of the file in S3, download the file (through the indirect/offline channel), and perform decryption on the client using the private key. Is that flow currently supported by the Encryption SDK?

**Comment by mattsb42-aws** [comment]
Let's start over. :)

Your requirements are to encrypt some data of arbitrary size on one place, send that encrypted data somewhere else, and decrypt it there. Both ends of this interaction have access to AWS credentials and can talk to AWS KMS.

Given the above, I would suggest simply using the AWS Encryption SDK (ESDK) with a symmetric AWS KMS CMK, as shown in this example[1].

The ESDK takes care of the complexities of envelope encryption for you (more on that here[2]). KMS takes care of protecting your wrapping key (the CMK) and controlling who and what can use that wrapping key (more on that here[3]). In this scenario you are using KMS in a similar way that you would use an HSM: your wrapping key never leaves KMS and instead you (or specifically the KMS master key provider) ask KMS to do things with it: in this case generating, encrypting, and decrypting symmetric data keys.

If you want the different components of your service to have different access (ex: one end can only encrypt and the other can only decrypt), you can control that using IAM and KMS access policies (more on that here[4]).

[1] https://github.com/aws/aws-encryption-sdk-java/blob/master/src/examples/java/com/amazonaws/crypto/examples/masterkeyprovider/awskms/SingleCmk.java
[2] https://docs.aws.amazon.com/encryption-sdk/latest/developer-guide/introduction.html
[3] https://docs.aws.amazon.com/kms/latest/developerguide/overview.html
[4] https://docs.aws.amazon.com/kms/latest/developerguide/control-access.html

**Comment by rajat210991** [comment]
So as per what @ajhool has mentioned, we are also looking to create a CMK and using that CMK generate a dataKeyPair. Using one of the keys of dataKeyPair(plaintext public key) we would encrypt the data and using the private key we want to decrypt the data. But it seems the AWS ESDK doesn't support asymmetric encryption.

**Comment by acioc** [comment]
The AWS Encryption SDK does not support AWS KMS asymmetric CMKs, but it does support RSA keys. However, from Matt’s notes and the responses above, it sounds like your use case can likely use a symmetric AWS KMS CMK.

I am linking this issue to https://github.com/awslabs/aws-encryption-sdk-specification/issues/64 in our specification, which covers asymmetric key support in the AWS Encryption SDK, since this feature request would cover multiple AWS Encryption SDK languages.

Please re-open this issue or cut us a new issue if you have additional questions.
