### ISSUE TITLE
Bug: OIDC tokens don't work

### ISSUE THREAD

**Issue by mszumilak** [aws/aws-encryption-sdk-java#185]
I am not able to use IRSA on EKS.

Currently aws-encryption-sdk-java is basing on aws-java-sdk 1.11.677

OIDC tokens are supported from 1.11.704 (https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts-minimum-sdk.html)

Please bump up dependencies, it should solve the issue.

**Comment by rradecki-migo** [comment]
I also really need the version to be updated, without it we cannot port part of our apps to EKS.

**Comment by lavaleri** [comment]
With #186 merged, this will be fixed in the next release. Thanks!

**Comment by lavaleri** [comment]
This was released as part of 1.6.2 https://github.com/aws/aws-encryption-sdk-java/releases/tag/1.6.2
