### ISSUE TITLE
Prevent aws-kms key namespace from being used in non-AWS KMS keyrings 

### ISSUE THREAD

**Issue by WesleyRosenblum** [aws/aws-encryption-sdk-java#188]
"aws-kms" as a key namespace is reserved for the AWS KMS Keyring. If a keyring supports a customer supplying the key namespace, they should not be allowed to use "aws-kms".

**Comment by mattsb42-aws** [comment]
instigated by: https://github.com/awslabs/aws-encryption-sdk-specification/issues/101
