### ISSUE TITLE
Chore: Audit Dependencies

### ISSUE THREAD

**Issue by texastony** [aws/aws-encryption-sdk-java#1892]
### Problem:

A number of dependencies were added as optional test dependencies that are actually transitive compile and runtime dependencies. 

https://github.com/aws/aws-encryption-sdk-java/blob/9297e1bad3860301bcf52b73466ec4b762e4f817/pom.xml#L82-L96

Additionally, if the ESDK-Java only depends on BC for ASN1 serialization, BC now offers an ASN1 utils library that should be smaller than the cryptographic package currently depended on. 

### Solution:

1. Remove the Dafny related dependencies that are already added to the compile and run class paths. 

2. [Try the BC utils package](https://www.bouncycastle.org/download/bcutil-jdk18on-177.jar). 

[//]: #  (NOTE: If you believe this might be a security issue, please email aws-security@amazon.com instead of creating a GitHub issue. For more details, see the AWS Vulnerability Reporting Guide: https://aws.amazon.com/security/vulnerability-reporting/ )

**Comment by imabhichow** [comment]
1. We [removed the Dafny-related dependencies](https://github.com/aws/aws-encryption-sdk-java/pull/1973) that were already in the compile and run class paths.
2. There are still a few ASN1 classes that we use in ESDK-Java that have not been included in the `bcutils-jdk18on` package. In addition, ESDK-Java also utilizes the [`org.bouncycastle.util.encoders.Base64`](https://github.com/aws/aws-encryption-sdk-java/blob/800bd0137c53f58bae2588945dab143a4c760224/src/main/java/com/amazonaws/encryptionsdk/internal/Utils.java#L17) class, which has not been included in the BC Utils package.
