### ISSUE TITLE
Need to encrypt and decrypt with separate AWS account. How to specify the AWS access key and secret key programatically

### ISSUE THREAD

**Issue by mkumar-creditshop** [aws/aws-encryption-sdk-java#1996]
### Problem:

How we can specify the AWS credentials here ?

        final MaterialProviders materialProviders = MaterialProviders.builder().MaterialProvidersConfig(MaterialProvidersConfig.builder().build()).build();
        final CreateAwsKmsMultiKeyringInput keyringInput = CreateAwsKmsMultiKeyringInput.builder().generator(keyArn).build();
        final IKeyring kmsKeyring = materialProviders.CreateAwsKmsMultiKeyring(keyringInput);

**Comment by texastony** [comment]
@mkumar-creditshop

If you do not want to use your environments default credentials,
you can use the Material Providers' `ClientSupplier` interface to programmatically build KMS Clients, given a region.

We have an example of this in another repo (that also uses the Material Providers Library and Keyrings):
- Here is a [demo ClientSupplier implementation](https://github.com/aws/aws-database-encryption-sdk-dynamodb/blob/5662be46cbbbc29f804340a9a64ab7b1bd2185be/Examples/runtimes/java/DynamoDbEncryption/src/main/java/software/amazon/cryptography/examples/clientsupplier/RegionalRoleClientSupplier.java#L18-L53)
- Here is a demo of [building a Keyring with that ClientSupplier](https://github.com/aws/aws-database-encryption-sdk-dynamodb/blob/5662be46cbbbc29f804340a9a64ab7b1bd2185be/Examples/runtimes/java/DynamoDbEncryption/src/main/java/software/amazon/cryptography/examples/clientsupplier/ClientSupplierExample.java#L57-L69)

I am going to close this issue,
as we have provided instructions on this.

If you have more questions, or the demo is not clear, feel free to open another GitHub issue.
