### ISSUE TITLE
Encryption Context for DecryptionMaterials on v3.0.0

### ISSUE THREAD

**Issue by alexyap1205** [aws/aws-encryption-sdk-java#2036]
Migrating from v2.4.1 to v3.0.0, we noticed that the DecryptionMaterials has an additional property encryptionContext. For 2.4.1, we didn't have this and we don't plan to use encryption context from Encryption SDK. However, upgrading to 3.0.0 requires us to provide an encryption context, otherwise DecryptionHandler fails with null exception. Should we just provide an emptyMap? Is it the same as saying there's no encryption context?

This is the piece of code from that throws null exception at runtime. TIA.

https://github.com/aws/aws-encryption-sdk-java/blob/19975b947177dee2618713f664043b4e980c772a/src/main/java/com/amazonaws/encryptionsdk/internal/DecryptionHandler.java#L798

**Comment by lucasmcdonald3** [comment]
Hi @alexyap1205,

Thanks for the report!
We are investigating this issue and may have identified an issue with custom CMMs from earlier versions of the ESDK.

Are you using a custom CMM?
If so, can you provide enough details about it so that we can produce this error?

Thanks,
Lucas

**Comment by lucasmcdonald3** [comment]
Hi @alexyap1205,

We recently released a patch to the ESDK (3.0.1) that fixes an issue with custom CMMs from earlier versions of the ESDK.

Could you consume this new version and let us know if it fixes your issue?

Thanks,
Lucas

**Comment by alexyap1205** [comment]
Hi @lucasmcdonald3, sorry I was busy with other things. Thanks for the fix. Will give it a go.

**Comment by ShubhamChaturvedi7** [comment]
@alexyap1205 Closing this issue since we have released the patch and haven't heard from you for some time. Feel free to re-open this if the original issue is still present in the patch.
