### ISSUE TITLE
Return nothing from Put Cache Entry in CMC

### ISSUE THREAD

**Issue by alex-chew** [aws/aws-encryption-sdk-java#207]
See awslabs/aws-encryption-sdk-specification#194.

Current implementation: https://github.com/aws/aws-encryption-sdk-java/blob/8f5f69e4981d42df3a845a3b18a3bd5580c94e19/src/main/java/com/amazonaws/encryptionsdk/caching/CryptoMaterialsCache.java#L43-L60

**Comment by lavaleri** [comment]
We are pursuing another mechanism to ensure that the implementation meets the specification.
