### ISSUE TITLE
Please don't deprecate AwsCrypto.encryptString/decryptString

### ISSUE THREAD

**Issue by dankirkd** [aws/aws-encryption-sdk-java#232]
The AwsCrypto.encryptString and AwsCrypto.decryptString methods are marked as deprecated (https://github.com/aws/aws-encryption-sdk-java/blob/master/src/main/java/com/amazonaws/encryptionsdk/AwsCrypto.java#L371), but the Javadoc also has a comment that actually makes the case for not deprecating these:

> {@code encryptString} and {@code decryptString} work as expected if you use them together.

There are use-cases where this is all that is needed, and additionally where passing around a byte array is not great, such as in JSON payloads.

Our particular case has us creating an encrypted string, to pass in such a payload.  It will then be echoed back in a callback from the remote system which will not be expected to do anything with it, and then it will only be decrypted by the same service/code that originally encrypted it.  So cross-language implementations issues are not a concern or relevant.

**Comment by robin-aws** [comment]
Hi there! The key point is `encryptString` is exactly equivalent to calling `encryptData` and then Base64 encoding the result, and similarly for `decryptString`. If you need that functionality, you can just apply the Base64 encoding and decoding yourself. The methods are deprecated because they don’t add any real value to the API, and aren't actually part of the specification of the core protocol: https://github.com/awslabs/aws-encryption-sdk-specification/tree/master/client-apis

**Comment by dankirkd** [comment]
@robin-aws One problem with implementing these methods myself is that I quickly run into the fact that the `CryptoResult` constructor is not public:

```
Error:(107, 16) java: <T,K>CryptoResult(T,java.util.List<K>,com.amazonaws.encryptionsdk.model.CiphertextHeaders) 
is not public in com.amazonaws.encryptionsdk.CryptoResult; cannot be accessed from outside package
```

i.e. I cannot call the following in my own code:

```
return new CryptoResult<>(Utils.encodeBase64String(ctBytes.getResult()),
                ctBytes.getMasterKeys(), ctBytes.getHeaders());
```

**Comment by lavaleri** [comment]
Hi @dankirkd, we do not support users creating their own `CryptoResult` objects. If you were relying on a `CryptoResult<String, K>` type in your code, you will need to refactor to use a `CryptoResult<byte[], K>` type.

I’m not sure what this refactor will look like for your code, but one way to do this could be to create your own helper class to pass around the results along with the base64 encoding of the payload.

**Comment by dankirkd** [comment]
This is all very nasty as a work around to just being able to call your deprecated methods.

**Comment by dankirkd** [comment]
How would I pass that around via JSON?
