### ISSUE TITLE
Is AwsCrypto reentrant?

### ISSUE THREAD

**Issue by kevinashaw** [aws/aws-encryption-sdk-java#240]
I posted this question to AWS Tech Support and they asked me to post it here.  I appreciate that this is a question and not an issue, however I am hopeful that I can get some help.  Thanks.

We are building a Java server application where we will be processing several thousand separate encrypted streams, with execution shared within a large thread pool.  Because each will require decryption, we need to access `AwsCrypto.builder().build()` in each instance.  However this means several thousand identical copies of the same object.  If the object is reentrant, we can create one instance, share the object across all streams and, I assume, save memory by eliminating redundant instances of AwsCrypto.  If it is not, we need to instantiate a separate instance of AwsCrypto in each stream instance.
My question: is AwsCrypto reentrant?

**Comment by farleyb-amazon** [comment]
Hi kevinashaw,

It is safe to use a single `AwsCrypto` instance across multiple threads, so you can certainly share the object across all your streams to save memory.

I’ll go ahead and close out this issue, but please feel free to re-open it or create a new one if you have any other questions.

Thanks,
Ben

**Comment by kevinashaw** [comment]
Thank you.
