### ISSUE TITLE
Support decryption verification after encryption

### ISSUE THREAD

**Issue by adam-aws** [aws/aws-encryption-sdk-java#279]
### Feature Request:

Ask to support decryption verification check right after the encryption finishes to make sure there is no corruption that happened when encrypting the data in the first place.

We currently have this workflow where we encrypt messages and to make sure the message can be decrypted successfully before storing it, it would be helpful if this check was done in the Encryption SDK to prevent having repeat this workflow in every system where we implement encryption.

**Comment by farleyb-amazon** [comment]
Hey Adam, thanks for this PR. I've gone ahead and created a corresponding issue in our spec repo (https://github.com/awslabs/aws-encryption-sdk-specification/issues/235). We'll need to think a bit more deeply about the design to make sure it works nicely with all the languages we support, so for now we won't be able to accept this PR. But I've linked it to the issue in the spec repo to make sure we consider this approach when we start implementing it.

I'm going to go ahead and close this out in favor of https://github.com/awslabs/aws-encryption-sdk-specification/issues/235, but please do feel free to update that issue with any additional thoughts.

Thanks,
Ben

**Comment by adam-aws** [comment]
Thanks for the feedback, looking forward for this change!
