### ISSUE TITLE
Remove hard cryptographic dependency on BouncyCastle

### ISSUE THREAD

**Issue by SalusaSecondus** [aws/aws-encryption-sdk-java#41]
Right now this code depends on BouncyCastle for several cases:

- [x]  EC Key generation (to support next point)
- [x] EC Key (de)serialization with point-compression
- [x] RSA encryption/decryption (due to default java JCE problems with OAEP not using SHA-1)
- [x] ECDSA signatures
- [x] HMAC-based Extract-and-Expand Key Derivation Function

To make this library more portable, we should remove all of these hard dependencies. This will require:
* Implementing point (de)compression
* Properly using AlgorithmParameterSpec to configure the JCE provider to do the right OAEP padding
* Replace HKDFBytesGenerator with Hkdf.java from aws-dynamodb-encryption-java
* Remove all other references to BouncyCastle.

**Comment by fieldju** [comment]
What is the status of this issue?

**Comment by fieldju** [comment]
@mattsb42-aws what is the status of this issue?

**Comment by mattsb42-aws** [comment]
Adding here for reference: when we do the point decompression, we need to make sure that we cover this too: https://github.com/aws/aws-encryption-sdk-python/issues/113

**Comment by ragona** [comment]
@fieldju We're taking a look at this one right now. I'll post again when we have a more concrete update, but I wanted to let you know that we're on it!

**Comment by SalusaSecondus** [comment]
Confirmed that all hard cryptographic dependencies on BouncyCastle  have been removed. This means that while BouncyCastle is still being used, it is only for parsing and support logic.

Critically, it means that it can also be swapped out for the FIPS validated provider. The following diff still passes all tests:
```
diff --git a/pom.xml b/pom.xml
index 3a2f2d3..ce56b08 100644
--- a/pom.xml
+++ b/pom.xml
@@ -48,8 +48,8 @@

         <dependency>
             <groupId>org.bouncycastle</groupId>
-            <artifactId>bcprov-ext-jdk15on</artifactId>
-            <version>1.61</version>
+            <artifactId>bc-fips</artifactId>
+            <version>1.0.1</version>
         </dependency>

         <dependency>
```

Excellent work @WesleyRosenblum !
