### ISSUE TITLE
Readme example uses deprecated functions

### ISSUE THREAD

**Issue by ewanmellor** [aws/aws-encryption-sdk-java#419]
### Problem:

The example code in the Getting Started section of the readme uses `AwsCrypto.encryptString` and `AwsCrypto.decryptString`, which are deprecated.

**Comment by josecorella** [comment]
Hi @ewanmellor 👋!

Thank you for bringing this to our attention. We have opened a PR, #423 updating the README with the latest methods.

Best,

**Comment by josecorella** [comment]
PR has been merged in 😁

**Comment by scottkennedy** [comment]
You replaced `crypto.decryptString(prov, ciphertext);` with `crypto.decryptData(prov, ciphertext);`, which as far as I can tell, was also deprecated.

**Comment by ewanmellor** [comment]
@scottkennedy Not in 2021 it wasn't.

**Comment by scottkennedy** [comment]
Sorry, didn't realize the age of this issue.
