### ISSUE TITLE
Serialization of encryption context needs to check for single too-long key or value

### ISSUE THREAD

**Issue by david-koenig** [aws/aws-encryption-sdk-java#55]
Serialization format of encryption context does not allow any individual key or value to be longer than 2^16-1 bytes. Does serialization code check for this limitation? Do we have test vectors that detect this issue?

**Comment by lavaleri** [comment]
This is done in https://github.com/aws/aws-encryption-sdk-java/blob/275ce526953ecf8f8f2f94ba38dcdf92e35c84bf/src/main/java/com/amazonaws/encryptionsdk/internal/EncryptionContextSerializer.java#L99-L102
