### ISSUE TITLE
Performance hit after using AWS Encryption SDK vs Bouncy Castle SDK

### ISSUE THREAD

**Issue by biharibipin** [aws/aws-encryption-sdk-java#75]
Hi,

Can I use AWS Encryption SDK to encrypt/decrypt a plaintext data of 32 char without using KMS service?

I would like to provide my own SECRET KEY to encrypt/decrypt data. I have used bouncy castle SDK to do that but it takes 40 seconds to process 1 million encrypt/decrypt. Can AWS Encryption SDK help to improve performance of 1 million encrypt/decrypt to 20 seconds?

Thanks,
Bipin

**Comment by johnwalker** [comment]
Hi! Yes, it's fine to encrypt or decrypt without using KMS.

No, the Encryption SDK will not help improve performance over bouncy castle.

**Comment by SalusaSecondus** [comment]
Closing as asked and answered.
