### ISSUE TITLE
Any plan to port this to C/C++ 

### ISSUE THREAD

**Issue by wghammas** [aws/aws-encryption-sdk-java#82]
Hi all,

 DO you have any porting to C/C++ or will it be introduced in the AWSSDKC++?

Thanks a lot,
WissaM

**Comment by johnwalker** [comment]
We can't comment on our plans, but we'll let you know if we release one. We're glad to hear that you're interested in an sdk for C or C++.

**Comment by johnwalker** [comment]
We followed up with a team discussion about your inquiry and have a more detailed answer. The AWS Encryption SDK will continue to be its own software package in all supported languages, and will not be folded into any of the general AWS SDKs. We are currently working on the AWS Encryption SDK for C but do not yet have a release date. We also have long-term plans to port the AWS Encryption SDK to a number of other languages, and will provide updates as they become available.
 
We will keep this issue open and update it when we have more information about the delivery of the C/C++ version.

**Comment by david-koenig** [comment]
FYI, we have just made the C/C++ port of this public at https://github.com/awslabs/aws-encryption-sdk-c

We welcome your feedback on it.

**Comment by wghammas** [comment]
Thanks a lot, David I'm already compiling and testing it , I will keep you update in case I need help.
