### ISSUE TITLE
AWS SDK and version policy unclear

### ISSUE THREAD

**Issue by wduminy** [aws/aws-encryption-sdk-java#834]
The [README](https://github.com/aws/aws-encryption-sdk-java) says `(The AWS Encryption SDK for Java does not support the AWS SDK for Java 2.x.)`

It also says to use:
```
<dependency>
  <groupId>com.amazonaws</groupId>
  <artifactId>aws-encryption-sdk-java</artifactId>
  <version>2.4.0</version>
</dependency>
````

The [support policy](https://github.com/aws/aws-encryption-sdk-java/blob/master/SUPPORT_POLICY.rst) says `The AWS Encryption SDK follows the same major version lifecycle as the AWS SDK.`

So I wonder what the meaning is of `2.4.0` and which AWS SDK I should use with it.

**Comment by wduminy** [comment]
SDK version `<aws.java.sdk.version>2.17.136</aws.java.sdk.version>` (from the examples) works.  
Seems that a minor update to `README.md` is required.

**Comment by texastony** [comment]
Howdy @wduminy,

You are correct.
The README is inaccurate.
Thank you for bringing this to our attention.
I have opened a PR to fix this.

Much Obliged,
AWS Crypto Tools
