### ISSUE TITLE
jce KeyStoreProvider fails to properly decrypt data keys

### ISSUE THREAD

**Issue by spickelmier** [aws/aws-encryption-sdk-java#85]
The JCE KeyStoreProvider is using the encrypted data key provider info to look up keys in the KeyStore, but the provider info is the combination of the key id and the wrapping data.  As a result, the key lookup always fails and the data key can not be decrypted.  This is for the case of symmetric keys.

-- setting up the provider info, contains the key id and the wrapping data
-- from encryptRawKey in jce/JceMasterKey
```
final byte[] provInfo = new byte[keyIdBytes_.length + wData.extraInfo.length];
System.arraycopy(keyIdBytes_, 0, provInfo, 0, keyIdBytes_.length);
System.arraycopy(wData.extraInfo, 0, provInfo, keyIdBytes_.length, wData.extraInfo.length);
return new DataKey<>(key, encryptedKey, provInfo, this);
```

-- trying to find a key in the keystore; will not find it since 'alias' contains more than the key id
-- from decryptDataKey in jce/KeyStoreProvider
```
final String alias = new String(edk.getProviderInformation(), StandardCharsets.UTF_8);
if (keystore_.isKeyEntry(alias)) {
  final DataKey<JceMasterKey> result = getMasterKey(alias).decryptDataKey(algorithm,
                        Collections.singletonList(edk),
                        encryptionContext);
  if (result != null) {
    return result;
  }
}
```

Not quite sure of the fix, need to get the size of the key id or wrapping data in order to properly extract the key id from the provider info, but it's not available within KeyStoreProvider.

**Comment by spickelmier** [comment]
I am currently using "BKS":
    KeyStore.getInstance("BKS", "BC");
But an open to other options with what JCE/Bouncy Castle support.

My current hack is this (and fails for keys that begin with the same prefix... again, a hack):

`USSFNRSPICKEL01:aws-encryption-sdk-java ricks$ git diff
diff --git a/src/main/java/com/amazonaws/encryptionsdk/jce/KeyStoreProvider.java b/src/main/java/com/amazonaws/encryptionsdk/jce/KeyStoreProvider.java
index 1e92cd2..5fd0553 100644
--- a/src/main/java/com/amazonaws/encryptionsdk/jce/KeyStoreProvider.java
+++ b/src/main/java/com/amazonaws/encryptionsdk/jce/KeyStoreProvider.java
@@ -178,6 +178,19 @@ public class KeyStoreProvider extends MasterKeyProvider<JceMasterKey> {
                             return result;
                         }
                     }
+                    // ugly hack, try to decrypt with each master key that matches the front...
+                    for (final String al : Collections.list(keystore_.aliases()))
+                    {
+                       if (alias.startsWith(al))
+                       {
+                               final DataKey<JceMasterKey> result = getMasterKey(al).decryptDataKey(algorithm,
+                                    Collections.singletonList(edk),
+                                    encryptionContext);
+                            if (result != null) {
+                                return result;
+                            }
+                       }
+                    }
                 }
             } catch (final Exception ex) {
                 exceptions.add(ex);
`

**Comment by spickelmier** [comment]
Easier to read, the full method:

    /**
     * Attempts to decrypts the {@code encryptedDataKeys} by first iterating through all
     * {@code aliasNames} specified in the constructor and then over
     * <em>all other compatible keys</em> in the {@link KeyStore}. This includes
     * {@code TrustedCertificates} as well as standard key entries.
     */
    @Override
    public DataKey<JceMasterKey> decryptDataKey(final CryptoAlgorithm algorithm,
            final Collection<? extends EncryptedDataKey> encryptedDataKeys,
            final Map<String, String> encryptionContext)
            throws UnsupportedProviderException, AwsCryptoException {
        final List<Exception> exceptions = new ArrayList<>();
        for (final EncryptedDataKey edk : encryptedDataKeys) {
            try {
                if (canProvide(edk.getProviderId())) {
                    final String alias = new String(edk.getProviderInformation(), StandardCharsets.UTF_8);
                    if (keystore_.isKeyEntry(alias)) {
                        final DataKey<JceMasterKey> result = getMasterKey(alias).decryptDataKey(algorithm,
                                Collections.singletonList(edk),
                                encryptionContext);
                        if (result != null) {
                            return result;
                        }
                    }
                    // ugly hack, try to decrypt with each master key that matches the front...
                    for (final String al : Collections.list(keystore_.aliases()))
                    {
                    	if (alias.startsWith(al))
                    	{
                    		final DataKey<JceMasterKey> result = getMasterKey(al).decryptDataKey(algorithm,
                                    Collections.singletonList(edk),
                                    encryptionContext);
                            if (result != null) {
                                return result;
                            }
                    	}
                    }
                }
            } catch (final Exception ex) {
                exceptions.add(ex);
            }
        }

        throw buildCannotDecryptDksException(exceptions);
    }
}

**Comment by karlw00t** [comment]
Thanks for the feedback.  We’ll look into a way that we can support symmetric master keys in the future.

**Comment by bbeck10** [comment]
Is there a plan for fixing this? It's pretty weird that the JCE KeyStoreProvider doesn't work for symmetric keys -- trying to use it for local development setup instead of KmsMasterKeyProvider.

**Comment by farleyb-amazon** [comment]
Hey bbeck10,

We don't have a specific plan for updating Master Key Providers; instead, we plan to move the Java Encryption SDK to our new and improved way of specifying wrapping keys, [Keyrings](https://docs.aws.amazon.com/encryption-sdk/latest/developer-guide/choose-keyring.html), which do support symmetric keys.

In the meantime, your best option for local development is likely to do some sort of mocking of KMS.

I'm going to close this out, but feel free to re-open or open another issue if you have any other questions.

Thanks,
Ben
