### ISSUE TITLE
provide public API for unpacking a header without decrypting a message

### ISSUE THREAD

**Issue by mattsb42-aws** [aws/aws-encryption-sdk-java#96]
We have had requests from customers to be able to unpack the header without attempting to decrypt the message, in order to make a decision about whether or not decryption should be attempted or how that decryption should be configured.

**Comment by softwareengineerprogrammer** [comment]
+1

**Comment by SalusaSecondus** [comment]
Please let me know if [ParsedCiphertext](https://github.com/aws/aws-encryption-sdk-java/blob/master/src/main/java/com/amazonaws/encryptionsdk/ParsedCiphertext.java) does what you need.  (Please be aware that the data you get back hasn't been authenticated and so isn't really trustworthy.)

**Comment by SalusaSecondus** [comment]
Closing this due to lack of response. We believe this solves the problem. Please re-open this issue if we are incorrect.
