### ISSUE TITLE
BouncyCastle FIPs Support

### ISSUE THREAD

**Issue by johnwalker** [aws/aws-encryption-sdk-java#99]
Can the Encryption SDK for Java be used with BouncyCastle FIPs?

**Comment by mattsb42-aws** [comment]
Yes[1]. Something that would be great to add to our CI is to run all of our tests with different JCE backends, much like we currently do with different JDKs.

[1] 99% certain. I'm pretty sure we've had people use it with that before.

**Comment by mattsb42-aws** [comment]
I stand corrected. #41 is blocking this.

**Comment by WesleyRosenblum** [comment]
Tests are now passing with FIPS certified Bouncy Castle

**Comment by ravinirmal10** [comment]
@WesleyRosenblum @SalusaSecondus - I am planning to use BC FIPS for `aws-encryption-sdk`. 

I can see that [pom.xml](https://github.com/aws/aws-encryption-sdk-java/blob/master/pom.xml) file of `aws-encryption-sdk` is having dependency of `bcprov-ext-jdk15on` jar, based on that it seems that if I want to use `bc-fips` then I need to copy the `aws-encryption-sdk` package and replace `bcprov-ext-jdk15on` to `bc-fips` in [pom.xml](https://github.com/aws/aws-encryption-sdk-java/blob/master/pom.xml). Basically I don't want to copy the package and want to use `aws-encryption-sdk` with BC-FIPS directly as a dependency in my project.

**Comment by WesleyRosenblum** [comment]
Hi @ravinirmal10,

The dependency on `bcprov-ext-jdk15on` is only needed for the AWS Encryption SDK to serialize and deserialize cryptographic objects, not for the underlying cryptography. From the [Getting Started](https://github.com/aws/aws-encryption-sdk-java#getting-started) section of the README:

> The AWS Encryption SDK for Java uses Bouncy Castle to serialize and deserialize cryptographic objects. It does not explicitly use Bouncy Castle (or any other [JCA Provider](https://docs.oracle.com/javase/8/docs/api/java/security/Provider.html)) for the underlying cryptography. Instead, it uses the platform default, which you can configure or override as documented in the [Java Cryptography Architecture (JCA) Reference Guide](https://docs.oracle.com/javase/9/security/java-cryptography-architecture-jca-reference-guide.htm#JSSEC-GUID-2BCFDD85-D533-4E6C-8CE9-29990DEB0190).
>...
> Beginning in version 1.6.1, the AWS Encryption SDK also works with Bouncy Castle FIPS (groupId: org.bouncycastle, artifactId: bc-fips) as an alternative to non-FIPS Bouncy Castle. For help installing and configuring Bouncy Castle FIPS properly, see [BC FIPS documentation](https://www.bouncycastle.org/documentation.html), in particular, User Guides and Security Policy.

To summarize, you do not need to modify the pom.xml of the AWS Encryption SDK. You may add Bouncy Castle FIPS as a dependency of your own software, and install it as mentioned in the [BC FIPS documentation](https://www.bouncycastle.org/documentation.html). Let me know if you have any further questions.

Thanks!
Wesley

**Comment by ravinirmal10** [comment]
@WesleyRosenblum - Thanks for your quick response, I am able to use `aws-encryption-sdk` with Bouncy Castle FIPS by adding `bc-fips` dependency in my project.
